# 1. THE APP: A simple "Hello World" web server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: traefik-v3
  labels:
    app: hello-k8s
spec:
  replicas: 2 # No. pods to see them "breathing" in the GUI
  selector:
    matchLabels:
      app: hello-k8s
  template:
    metadata:
      labels:
        app: hello-k8s
    spec:
      containers:
      - name: echo
        image: elsonpulikkan/echo-pod-name:latest
        ports:
        - containerPort: 80
---
# 2. THE SERVICE: Internal load balancer for the pods
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: traefik-v3
spec:
  selector:
    app: hello-k8s
  ports:
    - name: http
      port: 80
      targetPort: 80
---
# 3. THE ROUTE: Maps traffic from Port 8080 to our App
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: app-route
  namespace: traefik-v3
spec:
  parentRefs:
  - name: traefik-gateway
    namespace: traefik-v3
  rules:
  - matches:
    - path: { type: PathPrefix, value: / }
    backendRefs:
    - name: web-service
      port: 80
